# Generated by Django 5.1 on 2024-08-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('programming_language', models.CharField(max_length=32)),
                ('salary', models.IntegerField()),
                ('location', models.TextField()),
                ('is_remote', models.BooleanField()),
                ('level_need', models.CharField(max_length=32)),
                ('years_need', models.IntegerField()),
                ('skills', models.TextField()),
                ('english_lvl', models.CharField(max_length=32)),
                ('created_data', models.DateField()),
                ('parsing_data', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('raw_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.rawvacancy')),
            ],
        ),
    ]
