# Generated by Django 5.1 on 2024-08-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_vacancy_created_data_alter_vacancy_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvacancy',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
