# Generated by Django 5.1 on 2024-08-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rawvacancy_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawvacancy',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
