# Generated by Django 5.1 on 2024-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_salary_vacancy_salary_max_vacancy_salary_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvacancy',
            name='source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
