# Generated by Django 5.1 on 2024-09-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_usersearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserfields',
            name='telegram_chat_id',
        ),
    ]
