# Generated by Django 5.1 on 2024-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_additionaluserfields_telegram_chat_id'),
        ('job', '0006_rawvacancy_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='vacancy',
            field=models.ManyToManyField(blank=True, null=True, to='job.vacancy'),
        ),
    ]
